### ISSUE TITLE
did you forget to REVERT?

### ISSUE THREAD

**Issue by shadowadler** [dylan-jayatilaka/tonto#13]
When running tonto in conjunction with CrystalExplorer v3.1 to generate electron density mapped to the Hirschfeld surface, the following error is encountered:

Error in TEXTFILE:read_line_external ... unexpected end of file -- did you forget to REVERT?

The operating system is Windows 7.

**Comment by dylan-jayatilaka** [comment]
Ah, I didn't see this, you need to supply the CIF. I think I can regenerate what you were doing.

**Comment by shadowadler** [comment]
No worries, but I'm afraid I no longer have access to the data I was working with!
