### ISSUE TITLE
A compile error occured in crystal.F90

### ISSUE THREAD

**Issue by NKUCodingCat** [dylan-jayatilaka/tonto#14]
I clone the git and follow readme step by step and I got 

```
/Downloads/tonto/build/crystal.F90:7188.24:

      if (fit_finished_(self%data)) then
                        1
Error: Procedure argument at (1) is INTENT(IN) while interface specifies INTENT(INOUT)
```

OS             RedHatEnterpriseServer 6.8
CMake       3.6.2
Make          3.81
gfortran     gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
blas            3.2.1-4.el6  
lapack       3.2.1-4.el6

I am freshman in Fortran and I don't know where goes wrong, so I paste everything I know here, hope it can be solved.

**Comment by dylan-jayatilaka** [comment]
Hi JingTao,

Did you download from here, and follow those instructions?

https://github.com/dylan-jayatilaka/tonto

Also, we are now using gcc-6 and gfortran-6, you should try install those
for compilation.
(We test only on ubuntu). Finally, there are prebuilt executables here:

https://github.com/dylan-jayatilaka/tonto/releases

However, I would appreciate knowing if you are succesfu to build on Redhat,
so plese continue and tell me.

Where are you from? Which group?

Best

Dylan


---
Prof. Dylan Jayatilaka
School of Chemistry and Biochemistry
University of Western Australia
Work:   +61 8 6488 3138
Lab  :   +61 8 6488 4462
Mobile: +61 435441001
Skype:  dylan.jayatilaka

**Comment by NKUCodingCat** [comment]
Thank you for your Info, I do clone from git link as the github link you mentioned. And I try the prebuilt package and it works on my server, so I think that maybe I don't need to compile the source code for my works anymore, but I am appreciated to continue the test.   

By the way, I am from Nankai University, China and working as a visiting scholar in Dr. Tonglei Li in Purdue University, IPPH. I know your software by Crystal Explorer and I am trying to use python to call tonto automatically to process a large amount of crystal data and complete my guaduate thesis.

Thank you for your reply

**Comment by peterspackman** [comment]
Odds are the issue is with an outdated version of gfortran (gcc version 4.4.7 as you said). I’m fairly sure it will work with something like 4.9.1 or later, but we generally are using gfortran 6. If the binary releases are working for you, then it’s probably best to just use them!

**Comment by dylan-jayatilaka** [comment]
Hi JingTao,

AH yes, we met Prof. Li in Warsaw, it was interesting.

I agree with Peter's comment for tonto compilation - install newer gcc-6 -
but I need to check this later today as it is a serious problem.

We are also intending to process large amounts of data from
tonto, mainly for shape analysis, see below reference.

http://www.readcube.com/articles/10.1038/srep22204

But we are also intending to make HS and wavefunction information
available for a large part of the CSD. Do you plan something similar?
Please keep us informed, in case we duplicate work, or perhaps
we may collaborate to make the job easier.

Best

Dylan



best regards,

--dylan

Prof. Dylan Jayatilaka
School of Chemistry and Biochemistry
The University of Western Australia
Office : +61 8 6488 3138
Lab     : +61 8 6488 4462
Mobile: +61 435 44 1001
Skype : dylan.jayatilaka

**Comment by NKUCodingCat** [comment]
Actually I am working for matching the packing modes with molecule properties, basically I am working on small organic molecules, so your works may benefit me. Does the "information avavilable" you said means you calculate them and post on Internet or somewhere? That's cool.

By the way, I am just an undergraduate (IPPH in Purdue said I am a visiting scholar) and I am newer in Crystallography, I would be appreciated if I can help you in any case.

Again, Thank you for your info and thanks @peterspackman .

**Comment by NKUCodingCat** [comment]
Another question is, can tonto output a Gauss-like .cub/.cube file of HS and other properties(like d_norm etc.)? I am trying to unite the input format on my script. I cannot find a keyword for cube file, maybe there is not need to be calculate?

Anyway, thank you for your reply and your tonto

**Comment by dylan-jayatilaka** [comment]
> Actually I am working for matching the packing modes with molecule
> properties, basically I am working on small organic molecules, so your
> works may benefit me. Does the "information avavilable" you said means you
> calculate them and post on Internet or somewhere? That's cool.
>
Yes. Thank's for your feedback, we were wondering if such a resource would
be useful.

--dylan

**Comment by dylan-jayatilaka** [comment]
> Another question is, can tonto output a Gauss-like .cub/.cube file of HS
> and other properties(like d_norm etc.)? I am trying to unite the input
> format on my script. I cannot find a keyword for cube file, maybe there is
> not need to be calculate?
>
Yes, it can make cube files, but you have to modify
the tonto input file. You have to choose to edit the
tonto input file. You have to add the keyword

plot_grid= {
...
format= gaussian.cube
...
}

In the plot_grid= section

Unfortunately CrystalExplorer/tonto pair not made to be scripted so easily.
Tonto by itself is OK. For scripting you can also use

tonto -i <input-file -o <output-file>

Best

Dylan

**Comment by NKUCodingCat** [comment]
Wow, it is the best news I heard today. I think I don't need CrystalExplorer anymore. By the way, the documentation seems outdated for a long period in SF, do you have plans to update it? Just for curiosity.

Thank you

**Comment by dylan-jayatilaka** [comment]
Hi,

No, you dob't really need CrystalExplorer, but the majority cannot
work without GUI. But CrystalExplorer makes it easier to get coordinate
files sometimes.

SF is now just for historical interest. In fact there was never any
decent documentation for tonto. The best way is to look at the examples
in the tests/ folder.

Likewise, for allowed input keywords, just put a question mark anywhere
and it will tell you the allowed keywords; one day there may even be
an explanation of them, someone suggested that, but it will be a lot
of work.

Best

Dylan

best regards,

--dylan

Prof. Dylan Jayatilaka
School of Chemistry and Biochemistry
The University of Western Australia
Office : +61 8 6488 3138
Lab     : +61 8 6488 4462
Mobile: +61 435 44 1001
Skype : dylan.jayatilaka

**Comment by NKUCodingCat** [comment]
Thank you for your suggestion, I will keep searching in tests/examples and putting question mark everywhere. And....the most annoying work in programming is comment, isn't it? 

Thank you again, for your information and your help
