### ISSUE TITLE
Atom coordinate was not output as others do in UJIRIO

### ISSUE THREAD

**Issue by NKUCodingCat** [dylan-jayatilaka/tonto#15]
Hi dylan, I am working to get the atom coordinate which was used in CXS file, so I put a `put` after the `process_CIF` command, which was working good in some other crystal file but it not work in a crystal called UJIRIO. The cif made by Mercury and I am sure that the stdin file was absolutely same as other crystal used. I got confused and could you please take a look on it?

OS: Windows 10 14393 & Linux Mint 18
Release of tonto: Latest for each OS

File was attached as follows, hope that helps
[attachment.zip](https://github.com/dylan-jayatilaka/tonto/files/528668/attachment.zip)

**Comment by peterspackman** [comment]
Hi, I'm a bit unclear what is not working. Is it just that you want the atomic coordinates of the cluster fragment in the stdout file? or of the asymmetric unit?

**Comment by NKUCodingCat** [comment]
just the  the asymmetric unit is enough

Alright.......it solved.......so how does the `low_verbosity_on` works......? it seems that it will disable an output section when it is too long, anyway, thank you for your info.

**Comment by peterspackman** [comment]
From having a look in the code it seems that if the fragment geometry has more than 100 atoms, and `low_verbosity_on` is true, then it will not put out the fragment data in `put` calls.

As to why: my guess is Dylan decided that was what was meant by low verbosity at some point? I don't really know.
