### ISSUE TITLE
numdiff

### ISSUE THREAD

**Issue by FlorianKleemiss** [dylan-jayatilaka/tonto#18]
Hey, just a quick sugestion,

since we basically need it to make sure the tests don't fail because of minor computational errors, why not make the git-available numdiff a dependency?

**Comment by peterspackman** [comment]
I wouldn't be against making it an optional dependency, I'll look into it. In all honesty the *right* way to do this would be to restructure how testing is done to have an executable or something per test. Or to use the SBF file output and their testing. Parsing text files for testing numbers is, by and large, a waste of time.

**Comment by peterspackman** [comment]
Pretty sure this counts as resolved now that I’ve removed the numdiff dependency altogether.
