### ISSUE TITLE
Memory-Problem

### ISSUE THREAD

**Issue by FlorianKleemiss** [dylan-jayatilaka/tonto#19]
I have observed, that if you run certain jobs, like the rubrene example from Malte tonto swallows at least 32 GB of RAM. This is a petty, since it then starts to use the swap, which makes it slow as hell if that is a HDD and no SSD.

The job that was giving problem was a calculation of a gaussian grid. I can see, that in the way the cube files are treated right now it will cause problems, when they are stored in memory, since at some point they will just be too big.
So why not write the whole vector in a sbf file and whenever it is needed load it again from there. Is there any urgent need to have everything stored in memory? I think it would be difficult to do a more efficient way of writing the cubes, since in your functions you calculate the values and only then call the print function, but if we didn't store them in memory but in a file and checked the existence of such a file before printing it in the right format i think we could be way more ressource efficient. I would be happy to help where i can but would first liek to hear your thoughts on that

**Comment by dylan-jayatilaka** [comment]
H,

Great night tonight!

On Fri, Jan 13, 2017, 09:49 FlorianKleemiss <notifications@github.com>
wrote:

> I have observed, that if you run certain jobs, like the rubrene example
> from Malte tonto swallows at least 32 GB of RAM. This is a petty, since it
> then starts to use the swap, which makes it slow as hell if that is a HDD
> and no SSD.
>
> The job that was giving problem was a calculation of a gaussian grid. I
> can see, that in the way the cube files are treated right now it will cause
> problems, when they are stored in memory, since at some point they will
> just be too big.
> So why not write the whole vector in a sbf file and whenever it is needed
> load it again from there. Is there any urgent need to have everything
> stored in memory?
>

No, no urgent need. But you need to calculate the density pieces in batches.


I think it would be difficult to do a more efficient way of writing the
> cubes, since in your functions you calculate the values and only then call
> the print function,
>

Yes

but if we didn't store them in memory but in a file and checked the
> existence of such a file before printing it in the right format i think we
> could be way more ressource efficient. I would be happy to help where i can
> but would first liek to hear your thoughts on that
>

  It's not the file writing that is the issue. It's the fact that you hold
the whole grid in memory. So you need to calculate each piece pf the grid.
You need to divide it into batches. I anticipated that. The plot_grid
module breaks the grid into chunks. But it isn't,'t actually used.

**Comment by FlorianKleemiss** [comment]
I recently went thorugh a complete HAR with tonto using valgrind (This takes quite some time and resources...) and what i found was, that the biggest loss in memory is not a direct loss, but indirectly losing big structrues of data. 

I will attach the most severe cases of memory losses reported in valgrind (there 368 memory leaks in the HAR that i ran). 
For those not familiar with valgrind: 

A direct loss is a variable which was referenced by a pointer, which has then been pointed to another location, without prevously freeing the memory allocated by the value this pointer pointed to, so there is a area of memory left, which is allocated but unreachable. 

Indirect losses are thing, which are still ponted to, but the element which pointed to these things was directly lost, therefore the things attached to the previous element are lost, e.g. if we say we have an atom, which was directly lost and taht atom had information attached to it like positions, ADPs, bond order or whatever, which are still associated with the atom, but the atom itself is not reachable any more, that is an indirect loss.


==22428== 2,047,680 (1,808,352 direct, 239,328 indirect) bytes in 30 blocks are definitely lost in loss record 350 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xBB1A0E: __mat_shell1pair_module_MOD_create (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xBB1F28: __mat_shell1pair_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226A9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D945D: __crystal_module_MOD_ls_structure_fit (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF297: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4147D8: __molecule_main_module_MOD_read_keywords (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x415629: __molecule_main_module_MOD_run (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4031A7: MAIN__ (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x402D5C: main (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== 2,322,088 (17,680 direct, 2,304,408 indirect) bytes in 10 blocks are definitely lost in loss record 354 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xAD3DB7: __interpolator_module_MOD_create_0 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xAD4120: __interpolator_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226F9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CCC5A: __molecule_scf_module_MOD_make_hirshfeld_atom_info (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CD905: __molecule_scf_module_MOD_make_r_core_matrix (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D6804: __molecule_scf_module_MOD_initialize_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D7256: __molecule_scf_module_MOD_usual_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF388: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4147D8: __molecule_main_module_MOD_read_keywords (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== 2,322,088 (17,680 direct, 2,304,408 indirect) bytes in 10 blocks are definitely lost in loss record 355 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xAD3DB7: __interpolator_module_MOD_create_0 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xAD4120: __interpolator_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226F9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CCC5A: __molecule_scf_module_MOD_make_hirshfeld_atom_info (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CD905: __molecule_scf_module_MOD_make_r_core_matrix (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D25FB: __molecule_scf_module_MOD_make_fock_matrix.constprop.7 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D683D: __molecule_scf_module_MOD_initialize_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D7256: __molecule_scf_module_MOD_usual_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF388: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== 4,567,240 (35,360 direct, 4,531,880 indirect) bytes in 20 blocks are definitely lost in loss record 356 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xAD3DB7: __interpolator_module_MOD_create_0 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xAD4120: __interpolator_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226F9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CCC5A: __molecule_scf_module_MOD_make_hirshfeld_atom_info (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CD905: __molecule_scf_module_MOD_make_r_core_matrix (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D25FB: __molecule_scf_module_MOD_make_fock_matrix.constprop.7 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D683D: __molecule_scf_module_MOD_initialize_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D7256: __molecule_scf_module_MOD_usual_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF1E5: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== 4,644,176 (35,360 direct, 4,608,816 indirect) bytes in 20 blocks are definitely lost in loss record 357 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xAD3DB7: __interpolator_module_MOD_create_0 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xAD4120: __interpolator_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226F9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CCC5A: __molecule_scf_module_MOD_make_hirshfeld_atom_info (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CD905: __molecule_scf_module_MOD_make_r_core_matrix (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D6804: __molecule_scf_module_MOD_initialize_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D7256: __molecule_scf_module_MOD_usual_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF1E5: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4147D8: __molecule_main_module_MOD_read_keywords (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== 6,812,392 (53,040 direct, 6,759,352 indirect) bytes in 30 blocks are definitely lost in loss record 358 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xAD3DB7: __interpolator_module_MOD_create_0 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xAD4120: __interpolator_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226F9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D945D: __crystal_module_MOD_ls_structure_fit (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF297: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4147D8: __molecule_main_module_MOD_read_keywords (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x415629: __molecule_main_module_MOD_run (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4031A7: MAIN__ (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x402D5C: main (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== 8,190,720 (7,233,408 direct, 957,312 indirect) bytes in 120 blocks are definitely lost in loss record 359 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xBB1A0E: __mat_shell1pair_module_MOD_create (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xBB1F28: __mat_shell1pair_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226A9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CCC5A: __molecule_scf_module_MOD_make_hirshfeld_atom_info (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CD905: __molecule_scf_module_MOD_make_r_core_matrix (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D25FB: __molecule_scf_module_MOD_make_fock_matrix.constprop.7 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D72A4: __molecule_scf_module_MOD_usual_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF388: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4147D8: __molecule_main_module_MOD_read_keywords (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== 10,238,400 (9,041,760 direct, 1,196,640 indirect) bytes in 150 blocks are definitely lost in loss record 363 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xBB1A0E: __mat_shell1pair_module_MOD_create (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xBB1F28: __mat_shell1pair_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226A9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CCC5A: __molecule_scf_module_MOD_make_hirshfeld_atom_info (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CD905: __molecule_scf_module_MOD_make_r_core_matrix (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D25FB: __molecule_scf_module_MOD_make_fock_matrix.constprop.7 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D72A4: __molecule_scf_module_MOD_usual_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF1E5: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4147D8: __molecule_main_module_MOD_read_keywords (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== 27,788,528 (212,160 direct, 27,576,368 indirect) bytes in 120 blocks are definitely lost in loss record 367 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xAD3DB7: __interpolator_module_MOD_create_0 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xAD4120: __interpolator_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226F9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CCC5A: __molecule_scf_module_MOD_make_hirshfeld_atom_info (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CD905: __molecule_scf_module_MOD_make_r_core_matrix (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D25FB: __molecule_scf_module_MOD_make_fock_matrix.constprop.7 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D72A4: __molecule_scf_module_MOD_usual_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF388: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4147D8: __molecule_main_module_MOD_read_keywords (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== 34,831,320 (265,200 direct, 34,566,120 indirect) bytes in 150 blocks are definitely lost in loss record 368 of 368
==22428==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22428==    by 0xAD3DB7: __interpolator_module_MOD_create_0 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0xAD4120: __interpolator_module_MOD_create_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8226F9: __atom_module_MOD_copy (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x8D5289: __crystal_module_MOD_make_fragment_data.part.3 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CCC5A: __molecule_scf_module_MOD_make_hirshfeld_atom_info (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4CD905: __molecule_scf_module_MOD_make_r_core_matrix (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D25FB: __molecule_scf_module_MOD_make_fock_matrix.constprop.7 (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4D72A4: __molecule_scf_module_MOD_usual_scf (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4DF1E5: __molecule_tad_module_MOD_har_refinement (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x409EF8: __molecule_main_module_MOD_process_keyword (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==    by 0x4147D8: __molecule_main_module_MOD_read_keywords (in /home/florian/third_drive/tonto_Sylvia/build/tonto)
==22428==
==22428== LEAK SUMMARY:
==22428==    definitely lost: 23,554,467 bytes in 4,228 blocks
==22428==    indirectly lost: 87,409,223 bytes in 96,449 blocks
==22428==      possibly lost: 309,960 bytes in 8 blocks
==22428==    still reachable: 4,380 bytes in 29 blocks
==22428==         suppressed: 0 bytes in 0 blocks
