### ISSUE TITLE
cmake fails on Mac OS 10.13

### ISSUE THREAD

**Issue by MooersLab** [dylan-jayatilaka/tonto#24]
I get the following error message. It is true that /Users/blaine/software/tonto/external/sbf lacks a
CMakeLists.txt file. There is one in the higher directory but moving it to sbf leads to more errors. 
[CMakeOutput.log](https://github.com/dylan-jayatilaka/tonto/files/2929331/CMakeOutput.log)
[CMakeOutput.log](https://github.com/dylan-jayatilaka/tonto/files/2929332/CMakeOutput.log)

Blaines-MacBook-Pro:build blaine$ cmake ..
-- Found Perl: /usr/bin/perl (found version "5.18.2")
-- Found Git: /usr/local/bin/git (found version "2.19.1")
-- The Fortran compiler identification is GNU 6.3.0
-- The C compiler identification is AppleClang 10.0.0.10001145
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found BLAS: /opt/local/lib/libopenblas.dylib
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- CMAKE_BUILD_TYPE not provided, default: RELEASE
-- Fortran Compiler flags:  -fno-sign-zero -ffree-line-length-none -DGNU_gfortran -DGNU_gfortran_on_Darwin -mtune=generic -O -fbacktrace -DUSE_ERROR_MANAGEMENT -DINT_KIND=4 -DBIN_KIND=4 -DREAL_KIND=8 -DCPX_KIND=8 -DFLUSH
-- CXX Compiler Flags:
-- C Compiler Flags:
CMake Error at CMakeLists.txt:105 (add_subdirectory):
  The source directory

    /Users/blaine/software/tonto/external/sbf

  does not contain a CMakeLists.txt file.

-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Rules to process .foo -> .F90 using /usr/bin/perl
-- Configuring incomplete, errors occurred!
See also "/Users/blaine/software/tonto/build/CMakeFiles/CMakeOutput.log".

**Comment by FlorianKleemiss** [comment]
When doing a git clone please make sure to use the -recursive commandAm 05.03.2019 05:57 schrieb Blaine Mooers <notifications@github.com>:I get the following error message. It is true that /Users/blaine/software/tonto/external/sbf lacks a
CMakeLists.txt file. There is one in the higher directory but moving it to sbf leads to more errors.
CMakeOutput.log
CMakeOutput.log
Blaines-MacBook-Pro:build blaine$ cmake ..
-- Found Perl: /usr/bin/perl (found version "5.18.2")
-- Found Git: /usr/local/bin/git (found version "2.19.1")
-- The Fortran compiler identification is GNU 6.3.0
-- The C compiler identification is AppleClang 10.0.0.10001145
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found BLAS: /opt/local/lib/libopenblas.dylib
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- CMAKE_BUILD_TYPE not provided, default: RELEASE
-- Fortran Compiler flags:  -fno-sign-zero -ffree-line-length-none -DGNU_gfortran -DGNU_gfortran_on_Darwin -mtune=generic -O -fbacktrace -DUSE_ERROR_MANAGEMENT -DINT_KIND=4 -DBIN_KIND=4 -DREAL_KIND=8 -DCPX_KIND=8 -DFLUSH
-- CXX Compiler Flags:
-- C Compiler Flags:
CMake Error at CMakeLists.txt:105 (add_subdirectory):
The source directory
/Users/blaine/software/tonto/external/sbf

does not contain a CMakeLists.txt file.
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Rules to process .foo -> .F90 using /usr/bin/perl
-- Configuring incomplete, errors occurred!
See also "/Users/blaine/software/tonto/build/CMakeFiles/CMakeOutput.log".

**Comment by peterspackman** [comment]
As Florian mentioned,  the error is a result of an incomplete `git clone`. When cloning the tonto repository, you can do it with either `git clone --recursive`, or in an existing repository run `git submodule init && git submodule update`.

This is the case as tonto now uses git submodules (sbf is one of them) for external source dependencies. At some point I'll get around to setting up nightly builds of tonto so that compiling for MacOS, linux and windows will be largely unnecessary for anyone other than developers.

**Comment by MooersLab** [comment]
Thank you for the advice. I should have read the README.md file more carefully.
The compiling worked this time on a Mac OS 10.13.
Seven of 109 tests failed as expected for Mac.
