### ISSUE TITLE
Opening CIF file

### ISSUE THREAD

**Issue by DeAnte85** [dylan-jayatilaka/tonto#25]
When I generate a CIF from mercury then try to open in CrystalExplorer using Windows 10, I receive an error that says "There is an error in the Tonto stdout file, and no data has been loaded. The stdout file will be shown for inspection."

_______________________________________________________________

 T   O   N   T   O

 A free object-based system for computational chemistry

 Version: 17.04.29 v. 81192a3
 Platform: Windows
 Build-date: 2017-04-29 17:56

 For conditions of use, on-line documentation, and contributor
 and developer information see :-

 https://github.com/dylan-jayatilaka/tonto

 Dylan Jayatilaka
 Daniel Grimwood
 Peter Spackman
_______________________________________________________________

Timer started at 24/07/2019 20:45:00.

Error in TEXTFILE:open_new_file_for_write ... error opening new file C:/Users/DeAnt /Documents/Xray/19046_in_Pbca.cxc

File name   = stdin
Line number =   17
File buffer =     process_CIF_for_CX
Cursor ----------------------------^

**Comment by lomalaspina** [comment]
Hello DeAnts85, it seems like you have many directories with spaces on the name, I don’t remember well, but I think tonto will have a problem with that. Can you re-run with the cif file inside a path with no special characters of spaces? 

Cheers

Lorraine

**Comment by SubuhanAhamed** [comment]
Hello lomalaspina, The re-running - with the cif file inside a path with no special characters of spaces - is done, still it shows the similar problem in mine too.
