### ISSUE TITLE
Hirshfeld aspherical atom refinement error

### ISSUE THREAD

**Issue by chichenyulong** [dylan-jayatilaka/tonto#27]
Executing Hirshfeld aspherical atom refinement with Tonto always displays the following errors. For example, the nh3_rhf_DZP_HAR example in the tests folder. I tried several versions of Tonto with the same error.
----------------------------------------------------------------------------------------------
Error in VEC{BASIS}:read_library_data ... no library basis set

File name   = stdin
Line number =   56
File buffer =    }
Cursor ----------^

**Comment by FlorianKleemiss** [comment]
If you run the tests manually you need to specify the basis_set_directory keyword.if you built it on a computer run ctests to run the tests without specifying basis_set_dir

**Comment by chichenyulong** [comment]
> 
> 
> If you run the tests manually you need to specify the basis_set_directory keyword.if you built it on a computer run ctests to run the tests without specifying basis_set_dir

Thank you very much for your timely reply! The problem has been solved.
