### ISSUE TITLE
cmake error: does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by chichenyulong** [dylan-jayatilaka/tonto#29]
Hello,

I am trying to compile TONTO in CentOS 7 operating system. To do that I did the following:
1. Download tonto-17.04.tar.gz file from https://github.com/dylan-jayatilaka/tonto/releases.
2. type :
cmake .. -DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DMPI=1
I am getting the following error:
---------------
[root@localhost build]# cmake .. -DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DMPI=1
-- Found Perl: /usr/bin/perl (found version "5.16.3") 
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- The Fortran compiler identification is GNU 6.3.0
-- The C compiler identification is GNU 6.3.0
-- Check for working Fortran compiler: /home/openmpi303/bin/mpifort
-- Check for working Fortran compiler: /home/openmpi303/bin/mpifort  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /home/openmpi303/bin/mpifort supports Fortran 90
-- Checking whether /home/openmpi303/bin/mpifort supports Fortran 90 -- yes
-- Check for working C compiler: /home/opt/intel/compilers_and_libraries_2019.1.144/linux/mpi/intel64/bin/mpicc
-- Check for working C compiler: /home/opt/intel/compilers_and_libraries_2019.1.144/linux/mpi/intel64/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Building with MPI enabled
-- Found MPI_C: /home/opt/intel/compilers_and_libraries_2019.1.144/linux/mpi/intel64/bin/mpicc (found version "3.1") 
-- Found MPI_Fortran: /home/openmpi303/bin/mpifort (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI Fortran compiler: /home/openmpi303/bin/mpifort
-- MPI include: 
-- MPI libs:
-- CMAKE_BUILD_TYPE not provided, default: RELEASE
-- Compiler flags:  -fno-sign-zero -ffree-line-length-none -DGNU_gfortran -DGNU_gfortran_on_Linux -mtune=generic -O -fbacktrace -DUSE_ERROR_MANAGEMENT -DINT_KIND=4 -DBIN_KIND=4 -DREAL_KIND=8 -DCPX_KIND=8 -DFLUSH -DMPI
CMake Error at CMakeLists.txt:77 (add_subdirectory):
  The source directory

    /home/tonto-17.04/external/sbf

  **does not contain a CMakeLists.txt file.**

-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found BLAS: /usr/lib64/libblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Rules to process .foo -> .F90 using /usr/bin/perl
-- Configuring incomplete, errors occurred!
See also "/home/tonto-17.04/build/CMakeFiles/CMakeOutput.log".

**Comment by FlorianKleemiss** [comment]
The problem arises when you do not include the external dependencies during git clone. You need to run git clone --recursive in order to also get sbf and other dependencies.
delete your folder, download it with everything this Time and you should be fine.

**Comment by chichenyulong** [comment]
Thank you very much for you reply. Tonto compiled successfully.
