### ISSUE TITLE
What is the unit of the points of Hirshfeld surface in CXS file

### ISSUE THREAD

**Issue by NKUCodingCat** [dylan-jayatilaka/tonto#32]
Hi, I am trying to parsing cxs file and make my own wrl file using tonto-generated wrl. But I found a question that what exact the unit of coordinates of points in hirshfeld surface is. i.e. the unit of data in `vertices` section is Angstorm or Bohr. I think it should be Angstorm but I wanna double check it.

**Comment by peterspackman** [comment]
That will depend on the input file. By default I believe it's Bohr, but depending if you're talking about your own input file or one automatically generated by CrystalExplorer or something it may be different.

The `cx_uses_angstrom` keyword can change this in the input file. If you're uncertain I suggest loading it and seeing if the volume or surface area of the surface matches.

In short: it's probably Bohr.

If what you want to do is manipulate or work with surface files from CrystalExplorer, my suggestion is to use the SBF file format (supported by tonto and CrystalExplorer), for which I've written bindings for python, fortran, c and c++ here: https://github.com/peterspackman/sbf

**Comment by NKUCodingCat** [comment]
Thank you peter, that helps a lot
