### ISSUE TITLE
Fix unused variable warnings during compilation

### ISSUE THREAD

**Issue by peterspackman** [dylan-jayatilaka/tonto#4]
The following modules report these errors during compilation
- spherical.foo
- diffraction_data.foo
- vec{atom}.foo
- ~~isosurface.foo~~
- molecule.xtal.foo

Update this list as changes are made

**Comment by dylan-jayatilaka** [comment]
Mostly no warnings now. The following remain under linux/gfortran-6:

===
/home/dylan/github/tonto/debug/dft_functional.F90:1486:0:

subroutine new_u_B3LYP_x_energy_density(self,E,N0a,N0b,Nxa,Nya,Nza,Nxb,Nyb,Nzb)
Warning: ‘new_u_b3lyp_x_energy_density’ defined but not used [-Wunused-function]

/home/dylan/github/tonto/debug/dft_functional.F90:1505:0:

subroutine new_u_B3LYP_x_potential(self,V0a,V0b,N0a,N0b,Vxa,Vya,Vza,Vxb,Vyb,Vzb,Nxa,Nya,Nza,Nxb,Nyb,Nzb)
 Warning: ‘new_u_b3lyp_x_potential’ defined but not used [-Wunused-function]

====

Below can't be removed?

/home/dylan/github/tonto/debug/archive.F90:4149:33:
Warning: Integer division truncated to constant ‘1073741823’ at (1) [-Winteger-division]
/home/dylan/github/tonto/debug/archive.F90:4150:33:

====

/home/dylan/github/tonto/debug/molecule.fock.F90:4335:43:

       type(MOLECULE_TYPE) :: self
                                           1
Warning: Unused dummy argument ‘pa’ at (1) [-Wunused-dummy-argument]
/home/dylan/github/tonto/debug/molecule.fock.F90:4335:46:

       type(MOLECULE_TYPE) :: self
                                              1
Warning: Unused dummy argument ‘pb’ at (1) [-Wunused-dummy-argument]
/home/dylan/github/tonto/debug/molecule.fock.F90:3458:46:

 
                                              1
Warning: Unused variable ‘k_hf’ declared at (1) [-Wunused-variable]
/home/dylan/github/tonto/debug/molecule.fock.F90:3452:39:

       type(MOLECULE_TYPE) :: self
                                       1
Warning: Unused dummy argument ‘p’ at (1) [-Wunused-dummy-argument]

===

These can't be removed at this time.

/home/dylan/github/tonto/debug/molecule.tad.F90:1747:9:

          self%atom(a)%interpolator => interpolator(a)
         1
Warning: Pointer at (1) in pointer assignment might outlive the pointer target [-Wtarget-lifetime]
/home/dylan/github/tonto/debug/molecule.tad.F90:1787:12:

             self%atom(a)%interpolator => interpolator(a)
            1
Warning: Pointer at (1) in pointer assignment might outlive the pointer target [-Wtarget-lifetime]
/home/dylan/github/tonto/debug/molecule.tad.F90:1514:9:

          self%atom(a)%interpolator => interpolator(a)
         1
Warning: Pointer at (1) in pointer assignment might outlive the pointer target [-Wtarget-lifetime]

**Comment by dylan-jayatilaka** [comment]
I think we are nearly at the limit of what can be done by removing warnings for unused, now.
