### ISSUE TITLE
PURE procedures must be explicitly declared PURE

### ISSUE THREAD

**Issue by mbelgin** [dylan-jayatilaka/tonto#8]
Hi! 
I am helping cluster users to get tonto up and running, however I am seeing this error, regardless of the compiler I am using:

INTEL-mpif90-on-LINUX/fast/f95files/crystal.F90(9016): error #7137: Any procedure referenced in a PURE procedure, including one referenced via a defined operation or assignment, must be explicitly declared PURE.   [SYSTEM_LOCK_PARALLEL_DO]
      call SYSTEM_lock_parallel_do(tonto,"CRYSTAL:make_residual_error_map")
-----------^

I think this is related to this issue:

https://software.intel.com/en-us/articles/fdiag7137

I checked out the latest git version, which I believe is 3.2. Any suggestions?

Thanks!

**Comment by dylan-jayatilaka** [comment]
I believe this is now fixed when compiling under default settings (tested with gfortran-6)
