### ISSUE TITLE
v3.4.1 cif parsing fails hitting '?'

### ISSUE THREAD

**Issue by peterspackman** [dylan-jayatilaka/tonto#9]
most of the tests in tests_for_CX fail as a result of BUFFER:get_int being used to parse presumably optional/non-existent values.

**Comment by dylan-jayatilaka** [comment]
Hi - I just tried the tests on linux/gfortranh and they all passed ... ? which OS and compiler is this?

**Comment by peterspackman** [comment]
This was a while ago, and I believe it has since been fixed so I'll mark it closed.
